application: finalurl
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /.*
  script: main.app

# default_expiration: "4d 5h"

# instance_class: F1
# automatic_scaling:
#   min_idle_instances: 1
#   max_idle_instances: 2
#   min_pending_latency: 15.0s
#   max_pending_latency: automatic
#   max_concurrent_requests: 50
